### ISSUE TITLE
[BUG] Hypermapper client server

### ISSUE THREAD

**Issue by johanneslenfers** [rise-lang/shine#119]
## Preparation
- Install HM using pip: `pip install hypermapper`
- branch `git checkout autotune-jl` 

## Main files 
Tests in `src/test/scala/rise/autotune/hypermapper_client_server.scala` 
Python scripts in folder `autotuning`

## Test `minimal example` 
 - Starts `sub_proc_example.py` as subprocess and performs some communication

## Test `hm client server` [BUG]
 - Starts `hm_wrapper.py` as subprocess, which performs tuning in client server mode using `convolution.json`
 - `hm_wrapper.py` does not get a new request from HM, which means the `str_to_hypermapper` answer does not reach the `hm_wrapper.py`. 

### Test communication to HM
Running `python hm_wrapper.py --config_file convolution.json` 
- type in: `tile,vec,runtime,Valid`
- prints two random values (here called `x,y`) 
- type in: `x,y,1,True`
- type in: `x,y,1,True`
- New request is printed to the screen, which means, communication works fine

**Comment by michel-steuwer** [comment]
https://github.com/rise-lang/shine/commit/7a56adbd52ebead330177c7b92873aabf00bd3e4 fixes this bug and also adds an example of a simple direct `Scala <-> Hypermapper` communication.

The problem was that the parameter values were converted to floats before being passed back to Hypermapper (which Hypermapper does not handle gracefully) and that there is a `"Best point found:"` message send that is not described in the Hypermapper examples.
