### ISSUE TITLE
Type inference is not idempotent

### ISSUE THREAD

**Issue by Bastacyclop** [rise-lang/shine#31]
Running the recently modified type inference twice breaks the types of an expression.

**Comment by Bastacyclop** [comment]
Small example:
```scala
  // average two positive values rounding up
  val avg: Expr = dtFun(dt => dtFun(compute_dt => fun(
    dt ->: dt ->: dt
  )((a, b) => {
    val cast_ = fun(a => cast(a) :: compute_dt)
    cast((cast_(a) + cast_(b) + cast_(l(1))) / cast_(l(2))) :: dt
  })))

  test("success") {
    assert(IsClosedForm( infer(avg(i16)(i32))))
  }

  test("failure") {
    assert(IsClosedForm(infer(infer(avg(i16)(i32)))))
  }
```

**Comment by Bastacyclop** [comment]
@rise-lang/core I believe that type inference should either be idempotent, or infering types twice should be prevented (for example with `def infer(UntypedExpr): TypedExpr`).

**Comment by roger-uw** [comment]
> @rise-lang/core I believe that type inference should either be idempotent, or infering types twice should be prevented (for example with `def infer(UntypedExpr): TypedExpr`).

**How this issue occurs:**
For the `immutable.Map[K, +V]` trait used in `Solution`, when its size is less than or equal to 4, its concrete implementation is specialised `Map$Map1`, `Map$Map2`, `Map$Map3` and `Map$Map4`, which use `equals()` for key equality; for larger `Map`, the concrete implementation is `HashMap$HashTrieMap` which uses `hashCode()` for key equality.

For the expression in question, when we solve dependent function type constraint in the form of `(DepFunType(dta: DataTypeIdentifier, ta), DepFunType(dtb: DataTypeIdentifier, tb))`, a new **explict** `DataTypeIdentifier` is unified with the **implicit** copies of `dta` and `dtb`. Since `dta` and `dtb` are originally **explicit**, they have different hash codes with their **implicit** copies, and some expected substitutions may not be performed depending on the sizes of solutions.

This issue does not occur in the first attempt because no dependent function constraint is generated with type annotations which are completely removed after type inference. In the second run, the constraint generation process re-uses existing type information, generates dependent function type constraints, and eventually leads to this issue.

test code:
```scala
    val dtA = DataTypeIdentifier("dtA")
    val dtB = DataTypeIdentifier("dtB")
    val dtC = DataTypeIdentifier("dtC")
    val dtD = DataTypeIdentifier("dtD")
    val dtE = DataTypeIdentifier("dtE")
    val dtF = DataTypeIdentifier("dtF")
    val mapSmall: Map[Type, Type] = Map(dtA -> dtB, dtC -> dtB)
    val mapBig: Map[Type, Type] = Map(
      dtA -> dtB,
      dtC -> dtB,
      dtD -> dtB,
      dtE -> dtB,
      dtF -> dtB
    )

    println(mapSmall.getClass.getName) //should print "scala.collection.immutable.Map$Map2"
    println(mapBig.getClass.getName) //should print "scala.collection.immutable.HashMap$HashTrieMap"
    
    println(mapSmall.get(dtA.asExplicit)) //should print "Some(_dtB)"
    println(mapBig.get(dtA.asExplicit)) //should print "None"
```
**How to solve this issue:**
Implementing `hashCode()` method for type identifiers only based on their names.

**Comment by Bastacyclop** [comment]
@roger-uw Thanks for investigating this. The proposed solution seems appropriate to me since a name should uniquely identify identifiers. Another possibility is to explicitly use a map from string names to solution.
